the first change
milfokoh/p-one pull request #1
Opened 2024-03-11 11:43 UTC by milfokoh

2024-03-11 12:28 UTC, Anav11 requested changes

2024-03-11 12:28 UTC, Anav11 commented on index.css
> +
Отступ такой не нужен.

2024-03-11 12:28 UTC, Anav11 commented on index.css
> +
отступ не нужен

2024-03-11 12:28 UTC, Anav11 commented on index.css
> +.form-group{
Тут нужен отступ перед form-group

2024-03-11 12:28 UTC, Anav11 commented on index.css
> +label{
Лучше не вешать без необходимости классы на тэги (label, button, div, span, etc), а создать класс и навесить его

2024-03-11 12:28 UTC, Anav11 commented on index.css
> +form .p{
- отступ
- не вешать стили на form
- странно название .p для класса
- Везде нужен пробел после название класса, перед "{"

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +    <script>
Скрипт лучше вынести в отдельный файл index.js например и импортировать его
<script src="/script.js"></script>

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +    <!-- <script src="/script.js"></script> -->
Закомментированные куски кода - плохая практика (мусор)

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +    <script>
Вообще эта задача решается без js. Нужен чистый html.
Провалидировать форму на html.

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +    <div id="secondForm" class="form-group" style="display: none;">
Боюсь оно не будет норм отображаться в почтовом клиенте. Раньше вся верстка строилась на таблицах <tr><td>. Вообще все на страницах позиционировали с помощью таблиц, но прошли года и так больше не делают. НО это не касается почтовых клиентов, они умеют только в таблицы и тут ничего не поделать. Письмо нужно отверстать на таблице

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +     <form action="#" id="firstForm" class="myForm" >
В задаче было написано про семантические теги. Почитай о них и добавь в верстку

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +            <label for="YourName">Ваше имя</label>
в js принято писать camelCase, в html принято kebab-case
`your-name`
`form-input`
`check-btn`
и тд

2024-03-11 12:28 UTC, Anav11 commented on index.html
> +        <p> Для подтверждения перейдите по <a href = "https://ya.ru/" style="font-size: 14px;">ссылке.</a></p>
инлайн стили `style="font-size: 14px;"` плохая практика. Лучше все описывать в css файлах

2024-03-21 06:30 UTC, Anav11 approved these changes

2024-03-21 06:30 UTC, Anav11 commented on index.css
> +
Лишний отступ

2024-03-21 06:30 UTC, Anav11 commented on index.css
> +
лишний отступ

2024-03-21 06:30 UTC, Anav11 commented on index.css
лишний отступ

2024-03-21 06:30 UTC, Anav11 commented on index.css
> +
лишний отступ

2024-03-21 06:30 UTC, Anav11 commented on index.css
лишний отступ

2024-03-21 06:30 UTC, Anav11 commented on index.css
> +    margin: 0 0 9px 0 ;
margin-bottom: 9px

2024-03-21 06:30 UTC, Anav11 commented on index.css
> +    margin: 0 0 10px 0 ;
можно просто margin-bottom: 10px

2024-03-21 06:42 UTC, Anav11 commented
1) По тем комментариям, что сделала - ставь на них галку resolved и отправляй, чтоб они закрывались.
2) Не стоит делать коммиты для каждого файла (сейчас сделано 4 коммита), можно было сделать просто 2 коммита: первый коммит "init" (содержит html и css файл, из названия понятно что это первый инициализирующий коммит), второй коммит "fixes after review" (со всеми правками по html и css после ревью)
*[на будущее] Нужно стараться упростить ревьюеру понимание что было сделано и в комментарии кратко подсказывать что изменили. Обычно коммиты бьют логически: по сделанным блокам (компонентам/страницам/итд) или по одному типу изменений (например нужно во всем проекте изменить имя функции в 30 файлах).

2024-03-21 08:39 UTC, Anav11 requested changes

2024-03-21 08:39 UTC, Anav11 commented on index.html
> +            <section id="cell-names" class="cell-names">
Не думаю, что объединить label в section правильно.
HTML-элемент **section** представляет собой **автономный** раздел. 
Автомномны(самостоятельны) ли лейблы без инпутов?

2024-03-21 08:39 UTC, Anav11 commented on index.html
> +            <aside class="cell-input">
HTML-элемент **aside** представляет собой часть документа, чьё содержимое **только косвенно связанно** с основным содержимым документа. Чаще всего представлен в виде боковой панели, сносок или меток.

Мне кажется инпуты это не что-то второстепенное

example:

```
<article>
  <p>
    Мультфильм студии Уолта Диснея <em>Русалочка</em>
    был выпущен в 1989.
  </p>
  <aside>
    <p>Мультфильм заработал $87 миллионов во время первого выпуска.</p>
  </aside>
  <p>Подробнее об этом мультфильме...</p>
</article>
```

2024-03-21 08:39 UTC, Anav11 commented on index.html
> +            <nav id="label-notifications" class="label-notifications">Хочу получать уведомления</nav>
HTML-элемент **nav** определяет отдельную **секцию** документа, назначение которой обозначение **ссылок навигации** (как внутри текущего документа, так и ведущих на другую страницу). В качестве примера такой секции можно привести меню, якорные ссылки.

Не обязательно все ссылки должны быть обёрнуты в nav. nav следует использовать лишь для главных навигационных блоков. Например, [footer](https://developer.mozilla.org/ru/docs/Web/HTML/Element/footer) часто содержит список ссылок, которые не стоит оборачивать в [nav](https://developer.mozilla.org/ru/docs/Web/HTML/Element/nav)

2024-03-21 08:39 UTC, Anav11 commented on index.html
> +    <div id="input-form" class="input-form">
Зачем практически везде всем элементам даешь и id и class?

2024-03-23 10:03 UTC, milfokoh commented on index.html
> +    <div id="input-form" class="input-form">
Указываю class потому что привязываю к нему стили,  id потому что может возникнуть необходимость ссылаться на него. Вообще, я сомневаюсь в указании id, потому что не всегда понимаю ,когда действительно это нужно.

2024-03-23 10:03 UTC, milfokoh commented on index.html
> +        <label class="up-text">После вашего согласия на подписку вам будут приходить уведомления на почту и телефон</label>
Изменила nav на label, по смыслу больше подходит.

2024-03-23 10:03 UTC, milfokoh commented on index.html
> +            <fieldset id="cell-names" class="cell-names">
Попыталась сгруппировать по принципу семантики, с помощью fieldset, прочитала, что он используется для группировки нескольких элементов в форме. Создала две группировки, иной способ замены div.

2024-03-23 10:03 UTC, milfokoh commented on index.css
Только немного изменила параметры стилей и удалила отступы.

2024-03-23 10:03 UTC, milfokoh commented on index.html
> +                <legend id="label-notifications" class="label-notifications">Хочу получать уведомления</legend>
Добавила legend, он идет в комплекте, как заголовок fieldset.

2024-03-24 09:32 UTC, Anav11 commented on index.html
> +    <div id="input-form" class="input-form">
Ну вообще да, основное отличие, что id уникальный.
"может возникнуть необходимость ссылаться на него" - так делать не стоит. Есть такой принцип в проектировании YAGNI, можешь почитать.
Кратко: YAGNI («You aren't gonna need it»; с [англ.](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA) — «Вам это не понадобится») — процесс и принцип проектирования [ПО](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B5_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5), при котором в качестве основной цели и/или ценности декларируется отказ от избыточной функциональности, — то есть отказ добавления функциональности, в которой нет непосредственной надобности.

2024-03-24 09:37 UTC, Anav11 approved these changes

2024-06-30 12:57 UTC, merged